(specifications->manifest
 (list "sbcl"
       "sbcl-alexandria"
       "sbcl-cl-fad"
       "sbcl-cl-json"
       "sbcl-cl-str"
       "sbcl-cl-who"
       "sbcl-fiveam"
       "sbcl-hunchentoot"
       "sbcl-ironclad"
       "sbcl-legit"
       "sbcl-listopia"
       "sbcl-lmdb"
       "sbcl-parenscript"
       "sbcl-slynk"
       "sbcl-trivia"
       "sbcl-trivial-utf-8"))
