(defpackage :genodb/tests
  (:use :common-lisp :fiveam :genodb)
  (:import-from :genodb :genotype-matrix-matrix :genotype-matrix-metadata :import-into-genotype-db))

(in-package :genodb/tests)

(test test-genodb
  (let ((actual-genotype-matrix (read-geno-file "tests/test.geno")))
    (is (and (equalp (genotype-matrix-matrix actual-genotype-matrix)
                     (make-array (list 7 2)
                                 :initial-contents '((0 0)
                                                     (1 1)
                                                     (1 1)
                                                     (0 1)
                                                     (0 0)
                                                     (1 0)
                                                     (1 0))))
             (equalp (genotype-matrix-metadata actual-genotype-matrix)
                     '((("Chr" . "1")
                        ("Locus" . "rs31443144")
                        ("cM" . "1.50")
                        ("Mb" . "3.010274"))
                       (("Chr" . "2")
                        ("Locus" . "rs27644551")
                        ("cM" . "93.26")
                        ("Mb" . "173.542999"))
                       (("Chr" . "3")
                        ("Locus" . "rs31187985")
                        ("cM" . "17.12")
                        ("Mb" . "41.921845"))
                       (("Chr" . "4")
                        ("Locus" . "rs30254612")
                        ("cM" . "2.15")
                        ("Mb" . "3.718812"))
                       (("Chr" . "5")
                        ("Locus" . "UNCHS047057")
                        ("cM" . "3.10")
                        ("Mb" . "4.199559"))
                       (("Chr" . "X")
                        ("Locus" . "ChrXp_no_data")
                        ("cM" . "1.40")
                        ("Mb" . "3.231738"))
                       (("Chr" . "X")
                        ("Locus" . "Affy_17539964")
                        ("cM" . "1.40")
                        ("Mb" . "7.947581")))))))
  (finishes (let ((test-genodb "tests/test-genodb/"))
              (unwind-protect
                   (import-into-genotype-db "tests/test.geno" test-genodb)
                (fad:delete-directory-and-files test-genodb)))))

(run! 'test-genodb)
